version: '3.8'
services:
  traintickets:
    image: yasushma13/traintickets:latest
    ports:
       - "81:80"
    deploy:
       replicas: 3

  mobilerecharge:
     image: yasushma13/mobilerecharge:latest
     ports:
         - "82:80"
     deploy:
         replicas: 3
  movietickets:
     image: yasushma13/movietickets:latest
     ports:
         - "83:80"
     deploy:
         replicas: 3

  electricitybill:
     image: yasushma13/electricitybills:latest
     ports:
         - "84:80"
     deploy:
         replicas: 3

